### ISSUE TITLE
holdToDrag flag is not working in the rewrite

### ISSUE THREAD

**Issue by selvaa89** [timruffles/ios-html5-drag-drop-shim#103]
I see that there is no such flag in the rewrite.

Is there any other alternative or any plans to implement this in future?

I will be happy to help.

**Comment by reppners** [comment]
You're right, it is not implemented yet. Currently the alternative is to implement a dedicated drag handle element when scrolling and dragging need to coexist. See https://github.com/timruffles/ios-html5-drag-drop-shim/issues/75#issuecomment-253748658

It should be possible to implement a similar solution like in #76.

**Comment by altschuler** [comment]
Any updates on this? What needs to be done? Can I help? :)

**Comment by reppners** [comment]
Haven't had time to implement it yet but its on my todo list. Will accept PR's though!

Basically the 1.x solution can be applied in a similar way to 2.x

1.x solution:
https://github.com/timruffles/ios-html5-drag-drop-shim/blob/c3e8a0aa3753052795fd9e4c1195674361196b90/ios-drag-drop.js#L315-L333

2.x location:
https://github.com/timruffles/ios-html5-drag-drop-shim/blob/b485129b36fb875a072743df1a1d641b4183c34d/src/index.ts#L169-L176

`touchstart` in 1.x is roughly the same as the 2.x code above.

The plan is
* put the code for starting the drag operation (2.x location) into its own method, e.g. `initializeDragOperation`
* introduce `holdToDrag?:number` property in `Config` interface
* if/else based on `holdToDrag` presence at 2.x location
** false -> invoke `initializeDragOperation` directly
** true -> invoke logic for deferred drag start similar as in 1.x solution

**Comment by altschuler** [comment]
Awesome, thanks! I'll let you know if I take a stab at it :)

**Comment by matte00** [comment]
@altschuler Have you test @reppners's solution? I need delayDrag too =)

**Comment by altschuler** [comment]
FWIW I made a PR with @matte00's changes. Haven't found any issues with it yet :) Thanks a bunch both of you!

https://github.com/timruffles/ios-html5-drag-drop-shim/pull/112

**Comment by reppners** [comment]
`holdToDrag` is now released with v2.2.0 - thanks @matte00 and @altschuler 🎉
