### ISSUE TITLE
[2.x] dragOver, dragLeave, drop not fired

### ISSUE THREAD

**Issue by dirkluijk** [timruffles/ios-html5-drag-drop-shim#105]
In 2.0.0.rc-0, some events are not fired.

File to reproduce:

```
<!DOCTYPE html>
<html>
<head>
	<title>Drag/drop</title>
	<link rel="stylesheet" href="node_modules/drag-drop-polyfill/drag-drop-polyfill.css">
	<script src="node_modules/drag-drop-polyfill/drag-drop-polyfill.min.js"></script>
	<script src="node_modules/drag-drop-polyfill/drag-drop-polyfill-scroll-behaviour.min.js"></script>
	<script>
    DragDropPolyfill.polyfill({
        dragImageTranslateOverride: DragDropPolyfill.scrollBehaviourDragImageTranslateOverride
    });
    window.addEventListener( 'touchmove', function() {}); // fix for issue #77
	</script>
	<style type="text/css">
		.item {
			width: 200px;
			height: 200px;
			padding: 30px;
			margin: 10px 0;
			background: blue;
		}

		.item .draggable {
			padding: 20px;
			background: lightblue;
		}

		.droppable {
			width: 200px;
			height: 200px;
			padding: 30px;
			background: red;
		}

		.droppable.over {
			background: pink;
		}

		.droppable .inner {
			padding: 20px;
			background: orange;
		}
	</style>
	<style type="text/css">
		
	</style>
</head>
<body>

<div class="item">
	<div class="draggable" draggable=true>Lorem</div>
</div>

<div class="item">
	<div class="draggable" draggable=true>Ipsum</div>
</div>

<div class="droppable">
	<div class="inner">Some inner element</div>
</div>

<script type="text/javascript">
	var droppable = document.querySelector('.droppable');
    droppable.addEventListener('dragover', function (event) {
    	console.log('dragover');
    	event.preventDefault(); // Allows us to drop.
    	droppable.classList.add('over');
    });
    droppable.addEventListener('dragleave', function (event) {
    	console.log('dragleave');
    	droppable.classList.remove('over');
    });
    droppable.addEventListener('drop', function (event) {
    	console.log('DROP!');
    	droppable.classList.remove('over');
    });

    document.querySelectorAll('.draggable').forEach(function (draggable) {
		draggable.addEventListener('dragstart', function (event) {
	    	console.log('dragstart');
	    	event.dataTransfer.effectAllowed = 'move';
	    });
    });
</script>

</body>
</html>
```

**Comment by reppners** [comment]
Can you try to add a `dragenter` handler to your droppable which does invoke `event.preventDefault()`?

This is a requirement for the polyfill to work. I've written more detailed about this in the [README](https://github.com/timruffles/ios-html5-drag-drop-shim/tree/rewrite#cross-browser-differences-in-html5-dragndrop-api). 

> If no dragenter-handler is registered the drag-operation is silently allowed. Browsers don't implement dropzone-attribute according to caniuse so they allow it by default, which violates the spec. If a handler is set up it has to call event.preventDefault() to allow dropping. This is pretty bad for the polyfill since JS doesn't allow to check how many listeners were invoked when the event is dispatched, which forces the polyfill to rely on a listener being present calling event.preventDefault() to make it work.

This is kind of a bad side effect of implementing the spec very closely whilst not having the power that the browser has under the hood. If anybody has a suggestion to overcome this deviation to desktop browsers please let me know.

The README needs an obvious note that the `dragenter`-handler is a requirement.

**Comment by reppners** [comment]
btw if you need a drag and drop library for angular take a look at https://github.com/reppners/ngx-drag-drop

**Comment by dirkluijk** [comment]
Awesome, thanks!

Should have RTFM... :-)

**Comment by reppners** [comment]
Your welcome!

I'll reopen the issue until the documentation is improved 👍

**Comment by reppners** [comment]
Documentation enhanced in stable release 2.0.0
