### ISSUE TITLE
[2.x] "dragover" event on document not smooth

### ISSUE THREAD

**Issue by dirkluijk** [timruffles/ios-html5-drag-drop-shim#106]
I am positioning a custom helper element during the "dragover" events on my document.

On iOS/Android, where the polyfill is used, it is not as smooth as it would be with a "pointerover" event. But I can't use "pointerover", because HTML5 Drag/drop-browsers do not dispatch that event during dragging.

Can the polyfill dispatch "dragover" events faster (smoother) on tablets?

**Comment by reppners** [comment]
Try to lower the `iterationInterval` by initializing the polyfill with 
```JS
polyfill({
  iterationInterval: 50
});
```

Reference:
https://github.com/timruffles/ios-html5-drag-drop-shim/tree/rewrite#api--options-

**Comment by dirkluijk** [comment]
Awesome, sorry I didn't RTFM. :-)

**Comment by reppners** [comment]
No worries 👍 

Didn't do much testing with low iterationIntervals - I'm curious if it works well. Do you experience any negative side effects on performance with low `iterationInterval` values while dragging?

**Comment by dirkluijk** [comment]
No, it worked perfect on both Android and iOS. I used an interval of ``20``.

**Comment by reppners** [comment]
Yay :) Thx for the feedback :)
