### ISSUE TITLE
export detectFeatures function or somehow notify the environment that the polyfill is in use

### ISSUE THREAD

**Issue by lukaskral** [timruffles/ios-html5-drag-drop-shim#108]
Hello,

Thanks for publishing this package.

I'm using it on my project and now I'm trying to workaround the drag'n'drop from the host page into the child iframe (https://github.com/lukaskral/iframe-dnd-shim).

For this purpose it would be great to have an information whether your polyfill is in use or not. Do you think you could export your ```detectFeatures``` function or set up some global flag?

Thanks for your help,

Lukas

**Comment by reppners** [comment]
Very cool!

Would it be sufficient if the `polyfill()` method returned this information as boolean?

**Comment by lukaskral** [comment]
yes that would be definitely enough

**Comment by reppners** [comment]
There you go https://github.com/timruffles/ios-html5-drag-drop-shim/releases/tag/v2.1.0

**Comment by lukaskral** [comment]
that was fast. Thanks for your help!

**Comment by reppners** [comment]
No problem, iframe support is an open issue here so I'm very glad you're working on a pluggable solution. Can I link to your project for people that look for iframe support?

**Comment by lukaskral** [comment]
yes, sure, no problem. It's not published yet on the npm because it's still work in progress and it has its limitations but maybe it can inspire someone
