### ISSUE TITLE
Pseudo element styles (:before, :after) are not transferred to drag image node

### ISSUE THREAD

**Issue by macPOI** [timruffles/ios-html5-drag-drop-shim#109]
While I'm dragging my div-element my icons are not shown.
In the source code there is an implementation that removes all the class attributes of the drag element "dstNode.removeAttribute("class")".
Because of that the class attribut for my icon is removed and so the icon is not shown.
I'm using flaticon for my icons.
If I remove the line in index.min.js everything is working perfect.
Can you help me?
Is there a workaround?

**Comment by reppners** [comment]
Hmm thats odd - since the computed style is transferred to the drag image node the specific styles that make the icon render should also get transferred.

What technique is used in your icon css classes? Are there pseudo elements involved?

**Comment by macPOI** [comment]
Yes there are.

Here is one example:
.flaticon-sand-clock:before { content: "\f104"; }

and in my html i used it like:
<span class="flaticon-sand-clock"></span>

I should add, that in mozilla firefox it is working, but in google chrome not.
I dont know but maybe the property transfer doesn't work in chrome.
All other css property does work just fine.

**Comment by macPOI** [comment]
html:
span class="flaticon-sand-clock"

**Comment by reppners** [comment]
I'll try to figure out if pseudo element styles can be transferred imperatively.

Meanwhile as a workaround you can try to nest your draggable item inside another element which gets the draggable attribute.

```HTML
<span draggable="true"><span class="flaticon-sand-clock"></span></span>
```

**Comment by macPOI** [comment]
hey!
thank you!
Unfortunately the workaround did not wok.

**Comment by reppners** [comment]
Right.. forgot that its recursively removing classes. I'm afraid there is no temporary workaround for this other than manually removing the line you mentioned.

**Comment by macPOI** [comment]
Okay!
Thank you so far.
Maybe you can implement a config flag which controls if the class attribute is removed.

**Comment by macPOI** [comment]
Hey!
Do you have a solution for the problem?

**Comment by reppners** [comment]
I had no time yet to come up with a solution.

Most probably will include a new option which will enable you to provide the function that should return the node for using as drag image and will also export the function used as the default. This will enable users of the polyfill to implement their workarounds as needed.

**Comment by macPOI** [comment]
hey!
Ist's me again, could you implement you proposed solution?
Greetings Florian

**Comment by reppners** [comment]
API additions released as of v2.3.0-rc.0

**Comment by reppners** [comment]
Closing because a workaround is now available and documented.

**Comment by macPOI** [comment]
Thank you very much!


Mit freundlichen Grüßen

i.A. Ing. Florian Mack
System Engineering - CROSS 2


Telefon +43 (0)662 4670-6433
Telefax ---
Mobil ---
florian.mack@porscheinformatik.at

Porsche Informatik Gesellschaft m.b.H. | A – 5020 Salzburg | 
Louise-Piëch-Straße 9
Sitz: Salzburg | FN 72830 d / Landesgericht Salzburg | DVR 88439 | UID ATU 
36773309
http://www.porscheinformatik.at/




Von:    Stefan Steinhart <notifications@github.com>
An:     timruffles/ios-html5-drag-drop-shim 
<ios-html5-drag-drop-shim@noreply.github.com>
Kopie:  macPOI <florian.mack@porscheinformatik.at>, Author 
<author@noreply.github.com>
Datum:  23.01.2018 10:52
Betreff:        [Possible SPAM Low] Re: 
[timruffles/ios-html5-drag-drop-shim] Pseudo element styles (:before, 
:after) are not transferred to drag image node (#109)



Closing because a workaround is now available and documented.
