### ISSUE TITLE
drop not firing

### ISSUE THREAD

**Issue by ewaite-readingplus** [timruffles/ios-html5-drag-drop-shim#116]
I have all of the Events firing but I cannot get the drop to fire.  
I am using a Polymer 1.0 application, I have tried many different ways.  The drop fires in the browser, just not on the ipad.  Is there any suggestions you might have?  Thanks

**Comment by reppners** [comment]
Make sure to implement a dragenter listener
https://github.com/timruffles/ios-html5-drag-drop-shim/blob/master/README.md#polyfill-requires-dragenter-listener

**Comment by ewaite-readingplus** [comment]
Thank you, the new problem Im having is the shim only recognizes the tag as draggable on the ipad id the tag is a <a> anchor tag.  A <div> tag even with draggable = true doesnt work.

**Comment by reppners** [comment]
I close this one as solved, comment if you don't agree.
