### ISSUE TITLE
shim only working for anchor tags

### ISSUE THREAD

**Issue by ewaite-readingplus** [timruffles/ios-html5-drag-drop-shim#117]
For some reason, my <div draggable="true" tags are not recognized as draggable, but if the tags are <a> anchor tags they are.  Does anyone know why this is?

**Comment by reppners** [comment]
I need more info to help you, best would be a reproduction [plunkr](http://plnkr.co) or similar.

What libraries and technologies are involved? ShadowDOM, ShadyDOM? Show me your drag and drop handling code.

Can you include the unminified index.js of this polyfill and post the log output?

**Comment by ewaite-readingplus** [comment]
You can close this, Im working through the issues.  Im now trying to get ios10 working :/
Thanks for you help

**Comment by reppners** [comment]
That one might help you to get it working on iOS10 ;) https://github.com/timruffles/ios-html5-drag-drop-shim/issues/77

**Comment by ewaite-readingplus** [comment]
I appreciate it, I have been looking at that.  When I click, it does highlight dark grey, just no dragging on iOS 10.
Thanks.
