### ISSUE TITLE
Moving away from bower

### ISSUE THREAD

**Issue by sbatson5** [timruffles/ios-html5-drag-drop-shim#119]
Hi all. Thanks so much for this repo--it's been a huge help.  Would it be possible to move away from bower for this repo? This is currently our only bower dependency on a couple of projects.  Even bower itself doesn't recommend using bower anymore: https://bower.io/

**Comment by reppners** [comment]
It's available on npm.

https://www.npmjs.com/package/mobile-drag-drop

I don't have any strong opinion about keeping bower support, maybe some statistics can help on when to decide to drop bower support.

**Comment by reppners** [comment]
Closing because the package is available on npm.
