### ISSUE TITLE
iPad still not working

### ISSUE THREAD

**Issue by sendtoharmeet** [timruffles/ios-html5-drag-drop-shim#12]
This is working fine in android phone, but not working on iPad/iPhone

**Comment by jmeas** [comment]
Going to close, as this library was working for me on an iPad Mini 2.

@sendtoharmeet, if this is still a problem for you, **comment here** and we can continue the discussion. If you could create a JSFiddle or something showing the problem, that would be a great way for us to move forward.

Thanks!
