### ISSUE TITLE
Dragging canvases fix

### ISSUE THREAD

**Issue by johntdowney** [timruffles/ios-html5-drag-drop-shim#120]
Ran into this issue because I have canvas elements that need to be dragged and dropped, but this shim doesn't clone them correctly because it depends on `.cloneNode` which doesn't clone the image data for canvas elements.  Inserting this line:

`if(dstNode.nodeName=='CANVAS') dstNode.getContext('2d').putImageData(srcNode.getContext('2d').getImageData(0, 0, srcNode.width, srcNode.height), 0, 0);`

at Line 1297 of index.ts fixes the drag image to work for canvas elements or elements containing them.

**Comment by reppners** [comment]
Thanks for reporting and including your fix! Will be included in the upcoming maintenance release.
