### ISSUE TITLE
setDragImage() functionality not working

### ISSUE THREAD

**Issue by shah-dhaval** [timruffles/ios-html5-drag-drop-shim#121]
it seems like dragImageSetup property used for setDragImage. I have passed property through 
```
.polyfill({
dragImageSetup: function(element){ console.log(element)}
}) 
```
but it never get called, I also tried using forceApply but still it not called.

**Comment by reppners** [comment]
If you just want to set a custom drag image please use the html5 dnd api `setDragImage()`.

Sorry that the new options caused you confusion. They are currently only available on `v2.3.0-rc.0` - which version do you have installed?

`dragImageSetup` is NOT `setDragImage()`. I've updated the docs to make this more clear.

The purpose of `dragImageSetup` is solely to enable implementing a custom routine that creates a copy of the dragged element which is then used as the drag image. It is introduced to enable custom solutions needed for certain edge cases that the majority of users do not need and would bloat the polyfill with all kinds of workarounds.

**Comment by shah-dhaval** [comment]
Thanks for response
But html5 dnd api is not supported in IE version !!. And I want to set custom drag Image for IE version also. Do you have implemented polyfill for setDragImage?

**Comment by reppners** [comment]
This polyfill implements `setDragImage` but it does nothing special for IE. That means this polyfill will only work for touch-event initiated drag and drop.

If you need to support drag and drop initiated from mouse events than you need to apply another polyfill for `setDragImage` support. You might want to check out this polyfill https://github.com/MihaiValentin/setDragImage-IE

Which versions of IE do you need to support?
IEMobile 10 and 11 seem to have full drag and drop support without needing a polyfill, though I could never try it out first hand.

https://caniuse.com/#feat=dragndrop
https://msdn.microsoft.com/en-us/library/dn265022(v=vs.85).aspx

**Comment by shah-dhaval** [comment]
setDragImage-IE is not working in strict mode, 
Do you please also provide support for click-event initiated drag and drop ?
I am using for desktop browser IE11 and Edge.

**Comment by reppners** [comment]
IE11 and Edge are capable of HTML5 drag and drop natively, even on touch devices. 

Have you tried to execute this polyfill in IE11 with `forceApply` and then tried to use the `setDragImage()` api?

Though I don't recommend to apply the polyfill in a browser that handles drag and drop natively it might just work.

**Comment by shah-dhaval** [comment]
Yea but setDragImage not supported in that!!
I have customized setDragImage-IE for strict mode by passing event and now it's working for me.
Thanks

**Comment by reppners** [comment]
Great! Maybe you can post your solution on how to make it work in strict mode in in the repo https://github.com/MihaiValentin/setDragImage-IE

Closing as solved.
