### ISSUE TITLE
update `<a>` handling to match browser behaviour - fire clicks unless moving, when drag

### ISSUE THREAD

**Issue by timruffles** [timruffles/ios-html5-drag-drop-shim#23]
as per #22 

> However the browsers initiate their native drag handling only in special cases, when the mouse is moved a certain amount after being pressed down. Without sufficient movement, it's handled as a classic click.
> 
> Ideally we would like to have similar handling via touchmove and fallback to clicks without enough movement, however I've cooked up a faster fix for now.
> 
> With this patch, anchors are still draggable by default and handled as such. However if an anchor element doesn't have the draggable attribute explicitly set, then we also simulate a click event.

**Comment by java9394** [comment]
First of all, thanks for this great script.

I want to drag and drop a whole Div, which contains an image and href elements. So, I set draggable to false on the image and href elements.  This makes the link is not clickable.   I have to save the source element on touch start, and compare it with the target at touch end.  If they are the same element, I trigger the click event. It works beautifully now.

thanks.

steve
