### ISSUE TITLE
not working in safari 5.1.7 (7534.57.2)

### ISSUE THREAD

**Issue by sabs74** [timruffles/ios-html5-drag-drop-shim#32]
Maybe I am missing something... but using you demo located here: http://timruffles.github.io/ios-html5-drag-drop-shim/demo/ The drop target does not allow drops. I came here because I have noticed almost no drop targets are working on my safari except the jquery.ui one. Hope this helps and doesn't annoy someone!

**Comment by xStrom** [comment]
Safari 5.1.7 on Windows is a rather old browser from May 9, 2012. More importantly, HTML5 [drag & drop is broken](http://stackoverflow.com/questions/9671989/is-html5-drag-and-drop-broken-on-safari-browser-for-windows) in it.

Yes, this project here builds drag & drop support for Safari where that support doesn't exist. However, with a mobile focus. For ancient broken desktop versions of Safari you need something else.

**Comment by sabs74** [comment]
Thanks :) Yeah, trying other things and yes... its a horrible old browser (thanks apple for making sure devs have no life) with known issues. Just hoped this might help get around them.
Thanks for your reply :)
