### ISSUE TITLE
add a tag for a more recent release version

### ISSUE THREAD

**Issue by abbyhowell** [timruffles/ios-html5-drag-drop-shim#33]
the most recent release version is from Oct 28, 2013. If someone wants to use NPM to download this repo, they'll get a much older version.

**Comment by timruffles** [comment]
You're right! Will fix tomorrow

**Comment by timruffles** [comment]
Pushed - thanks :)

**Comment by abbyhowell** [comment]
There are three commits since the last release, including what seems like a fix to push the initial drag image offscreen before the drag event starts. Can you make another release? Thanks!
