### ISSUE TITLE
make a new release with most recent changes

### ISSUE THREAD

**Issue by abbyhowell** [timruffles/ios-html5-drag-drop-shim#38]
Can you folks make another release that includes the most recent changes, like the one that puts the drag image off screen instead of in the top-left-corner before the start of the drag event? The most recent release version 1.0.1 doesn't include those commits, which means I can't get them via bower. Thanks!

**Comment by timruffles** [comment]
done, thanks!

**Comment by abbyhowell** [comment]
@timruffles can you please add a tag for the release also? the most recent release according to git is still 1.0.1 which means i can get this baby through npm but not bower. Thanks!!

**Comment by timruffles** [comment]
done! got to get this release scripted :)

**Comment by abigezunt** [comment]
@timruffles thank you!!
