### ISSUE TITLE
Release on bower/npm

### ISSUE THREAD

**Issue by jmeas** [timruffles/ios-html5-drag-drop-shim#39]
I'd resolve #30 then release this lib. Atm I'm using git SHAs to track the dep, which works but semver versions are betta'

**Comment by jmeas** [comment]
Update: it's on npm as [`drag-drop-webkit-mobile`](https://github.com/timruffles/ios-html5-drag-drop-shim/blob/master/package.json#L2).

**Comment by timruffles** [comment]
Yup it's been there for a while. If you fancy rolling a bower package tho that'd be great.

**Comment by jmeas** [comment]
I'll do that. I suggest we:

1. Rename it per your suggestion
2. Deprecate the old npm package
3. Create the new one
4. Release on Bower

If you give me contrib rights on `npm` for this library, I can take care of pretty much all of that. I'll make issues for each step, so that you can follow along / offer suggestions before I do any changes :P

**Comment by reppners** [comment]
Any progress on plans to publish this module on bower?

**Comment by timruffles** [comment]
landed in https://github.com/timruffles/ios-html5-drag-drop-shim/releases/tag/v1.1.1 ! Thanks for reminding me

**Comment by reppners** [comment]
that was quick :+1:  thx
