### ISSUE TITLE
example of drag/drop site not working

### ISSUE THREAD

**Issue by bryndyment** [timruffles/ios-html5-drag-drop-shim#42]
http://tinymath.com/practice

Looks great, except it's snapping back upon release.

**Comment by jmeas** [comment]
Okay...can you provide more details? What device and browser?

**Comment by xStrom** [comment]
Seems to be working fine to me. So indeed, what device/os/browser are you seeing the issues with?

**Comment by bryndyment** [comment]
This is on iPad/iPhone, both iOS 8.3/Safari.

The problem seems to be not the drag/drop itself, but reading the clientX, clientY event attributes to keep the dragged item in place post-drop.  My code is based upon http://jsfiddle.net/robertc/kKuqH/ which, when adding the shim, shows the same problem.

On dragStart, I am doing this:

`_offsetX = _dragE.position().left - _e.originalEvent.clientX;`

... but `_e.originalEvent.clientX` is undefined (the JSFiddle isn't using jQuery, but I am ... thus `originalEvent`).

On drop, I am again referencing clientX and it's undefined as well.

Do you have any hints on how to determine the X/Y offset of the drag operation so as to reposition the dragged element at the drop site?

**Comment by bryndyment** [comment]
Since the incoming event doesn't appear to have any position-related information that I can use, I am now separately using touch events to track the change in position.  My guess is that, since the event being supplied is generated by the shim, it's simply not including clientX and related position information.

**Comment by xStrom** [comment]
Your guess is correct. The only positioning data currently included in the pageX/Y.

Of course it would be nice to include more. If the clientX/Y could just be taken from the touch event, then this would be a simple change.
