### ISSUE TITLE
Fix for iPad1

### ISSUE THREAD

**Issue by nitro52** [timruffles/ios-html5-drag-drop-shim#43]
Hi,
We have an iPad 1 that we were testing on an noticed that this library wasn't working. When we use chrome emulator we can reproduce the problem.
line 338 looks like it needs a check if srcNode.nodeType is an element before cloning the node. It was throwing an error here.

 
      // Clone the style
       if (srcNode.nodeType == 1) {
        var cs = window.getComputedStyle(srcNode);
        for (var i = 0; i < cs.length; i++) {
          var csName = cs[i];
          dstNode.style.setProperty(csName, cs.getPropertyValue(csName), cs.getPropertyPriority(csName));
        }
      }

**Comment by xStrom** [comment]
That check exists on line 330 of the master branch currently. Are you sure you tested the latest version of the library? Did you perhaps test using our demo pages? Because the demo pages used an outdated version of the library, which I have now fixed.

**Comment by nitro52** [comment]
Ahh yes, that would be the problem. We were testing the demo page to see if it would work for us.
