### ISSUE TITLE
Drop (dragend) does not work on iOS 8.4.1

### ISSUE THREAD

**Issue by chliebel** [timruffles/ios-html5-drag-drop-shim#46]
This shim does not seem to work on iOS 8.4.1: While starting a drag operation and dragging itself works, dropping does not. On previous versions of iOS, this works as expected.

**Comment by ishmaelAhmed** [comment]
This looks to be due to the way drop target is determined.
In ios 8.4 mobile safari what document.elementFromPoint() returns as the top most element has changed. I will supply examples when I get the chance.

**Comment by NoelAbrahams** [comment]
This demo from [spec-compliant rewrite](http://reppners.github.io/ios-html5-drag-drop-shim/spec-compliance/) works in iOS 8.4.1.
