### ISSUE TITLE
Alternate way of setting enter / leave support

### ISSUE THREAD

**Issue by derwaldgeist** [timruffles/ios-html5-drag-drop-shim#49]
Great library. Yet I'm having a problem enabling enter / leave support. There are frameworks out there that do not allow you to place static JS code before embedding a library, like Meteor (at least, they don't allow it without some hacking). So it would be great if enter / leave support would either be enabled by default, or if there were an explicit function call to trigger that support.

**Comment by xStrom** [comment]
This seems like a reasonable request.

Making this configurable post-load would require a bit of architectural changes, but could be done.

I like enabling these events by default more though. It's an easy change and I have it turned on for all my projects anyway. Based on the various bug reports that I've seen, people seem to use this functionality more than not, so it makes sense to make it the default in that sense as well. In addition, the rewrite branch already has it on by default.

@timruffles Do you see a problem with changing the default behavior as if `enableEnterLeave: true`?

**Comment by timruffles** [comment]
Nope that seems fine. Let's bump the major version number, and maybe add a
CHANGELOG.md so we're done our best to let people know.

**Comment by derwaldgeist** [comment]
Great!
