### ISSUE TITLE
Drop event needs dataTranser.dropEffect  property

### ISSUE THREAD

**Issue by joshuadmatthews** [timruffles/ios-html5-drag-drop-shim#54]
I am trying to use this with angular-dnd-lists https://github.com/marceljuenemann/angular-drag-and-drop-lists but it leverages the event.dataTransfer.dropEffect property to determine if the drag was aborted or not. Would there be any way to integrate that?

**Comment by timruffles** [comment]
Definitely welcome a PR!

**Comment by xStrom** [comment]
We now have a partial solution for this. It may be sufficient for your use case.

A more comprehensive solution will come when the major rewrite in #44 progresses.

**Comment by joshuadmatthews** [comment]
This does actually resolve the problem I was having.  Looking forward to the rewrite in #44
