### ISSUE TITLE
PreventDefault on drag start supported?

### ISSUE THREAD

**Issue by loopingLines** [timruffles/ios-html5-drag-drop-shim#57]
Hi,

Thanks a lot for writing this. You have made my life very easy.

There is one thing I am not able to work out. I need to prevent drag start on certain condition. preventDefault on drag start is not sufficient. 

I tried changing the code: called cleanup(making the function member of DragDrop and other necessary changes) but it wont work.

Please help

**Comment by loopingLines** [comment]
Ok, It does work. But I have to call cleanup in a timeout with some delay. But this is not helping much because the function in a timeout is called when there are no other events in stack. The dragImage is removed when I hold still, otherwise its there till I am interacting with the element.

Any ideas?

**Comment by loopingLines** [comment]
Alright. another update. I got is working without timeout by calling createDragImage before dispatchDragStart in DragDrop. 

Since dragStart is dispanced on touchstart, I am finding it hard to prevent my drag case. I have to first find the direction of drag and then decide if the drag is valid. Could also prevent the case if there was a drag event dispatched.

**Comment by xStrom** [comment]
Just to clear up something. Is this library not working correctly or are you just looking for general ideas how to solve your problem? That is, can you cancel the drag as you like on desktop browsers but the same code doesn't work with this library on mobile?

**Comment by loopingLines** [comment]
Apologies for my late response. 

The library is working just fine. But there are few things the library is not doing (on mobile) that is limiting. 

1. Preventing a drag start event.
2. dispatching the drag start on an actual drag rather than on touch start.

I can cancel the drag by preventing the dragstart event on desktop but cannot on mobile.

**Comment by xStrom** [comment]
Okay, canceling the `dragstart` event is now possible.

Regarding the fact that we currently send the `dragstart` event immediately and don't wait for an actual drag motion to happen. This is a known shortcoming of the library, documented as early as issue #23. Unfortunately no fix for this is planned in the short term. We would eventually like to have this solved, but currently it's waiting behind #44 - where we are working towards a complete rewrite of the library.

**Comment by bwu1** [comment]
I think I might have solved the issue of dragstart starting immediately issue. Let me know if this makes sense:

Change "touchstart" function to" touchmove" and replace doc.addEventListener("touchstart", touchstart); with doc.addEventListener("touchmove", touchmove);

Create a global variable-"stored_drag_object". Set this variable immediately in DragDrop(event, el). Unset this global variable in cleanup().

Meanwhile in touchmove- add this to the very beginning:
```
	  if(stored_drag_object!= null){
		  return;
	  }
```
Therefore touchmove is triggered by the movement of a touch, but the code is executed on the initial movement, mimicking "touchstart".

Does this make sense?

**Comment by reppners** [comment]
This issue is fixed in the rewrite #61
