### ISSUE TITLE
Ability to set needsPatch to `true` through config

### ISSUE THREAD

**Issue by ivynye** [timruffles/ios-html5-drag-drop-shim#63]
I've run into enough issues with userAgent sniffing that I want to be able to force this patch, if necessary.

Example use case is when the userAgent has been altered.

```
var needsPatch = !(dragDiv || evts) || /iPad|iPhone|iPod|Android|/i.test(navigator.userAgent) || !!config.needsPatch;
```

**Comment by timruffles** [comment]
Yup - I'd agree with you there. Will accept a PR.
