### ISSUE TITLE
Ability to "bind" only specif elements not the whole document

### ISSUE THREAD

**Issue by famoraes** [timruffles/ios-html5-drag-drop-shim#65]
Hey! First, thanks for the library, is awesome!
So, there's a way to bind only specif elements? e.g bind only a modal or a dropdown?
I'm having problems with a project. In this project with have a map using OpenMaps. This map is working with iPad, but once I activate the plugin (for another parts of the project) it's stop to work.

Thank you in advance.

**Comment by timruffles** [comment]
Not at the mo, as it's designed as a drop-in shim.

Would be fairly easy to add as a PR if you'd like. Something like:

```javascript
window.iosDragDropShim = { publishTo: "shim" }
```
and then the shim would be published to window.shim. Call that on an element per element basis.

If you'd like to add this we'd be happy to accept a PR!
