### ISSUE TITLE
image of dragged element is centered on this element

### ISSUE THREAD

**Issue by Adavo** [timruffles/ios-html5-drag-drop-shim#66]
Hello,

This issue is a bit hard to explain. I have created some illustration to show the issue.

When I start to drag an element on mobile, the "image" of this element is automatically centered where my finger is, which lead to very poor UX experience if the div is big, or if we use a specific element to reorder a list. Example:

![bug](https://cloud.githubusercontent.com/assets/17383022/13982899/7db506a8-f127-11e5-9c1e-e88af8b7e6c6.jpg)

On this example, I can only drag element by the small icon. When I start to drag an element by touching the small icon, the semi-transparent image (which represent the dragged element) is centered on the position of my finger. 

I think it will be better to don't center the semi-transparent image. Instead, the semi-transparent image should be positioned where the user touch the element.

![behavior](https://cloud.githubusercontent.com/assets/17383022/13983186/273bc68e-f129-11e5-8033-7c762a2f4d0c.jpg)

thanks

**Comment by reppners** [comment]
This is fixed in the rewrite #61.
