### ISSUE TITLE
Conflict Hammer JS iOS

### ISSUE THREAD

**Issue by yelhouti** [timruffles/ios-html5-drag-drop-shim#68]
First of all, thanks for the awesome library, it helps save a lot of time.
On the other hand, I'm trying to use enter leave with with hammer js, but events like press don't work anymore when I set `enableEnterLeave: true`. this doesn't happen on chrome browser but happens on iOS UiWebView. any suggestion on what might be the problem or how to find it please.

Thanks

**Comment by reppners** [comment]
Can you provide a plunkr or jsfiddle?

**Comment by yelhouti** [comment]
Sorry my bad, I had two script in the page on overriding setTimeout it was the one creating the problem with hammer.js not your's please delete this issue and sorry for the inconvenience

**Comment by reppners** [comment]
No problem, glad you could sort that issue out.
