### ISSUE TITLE
Uncaught ReferenceError: DEBUG is not defined

### ISSUE THREAD

**Issue by algodave** [timruffles/ios-html5-drag-drop-shim#71]
I installed release `2.0.0-beta.0` with bower and imported `drag-drop-polyfill.js` and `drag-drop-polyfill.css` in my EmberJS app, but when invoking `DragDropPolyfill.Initialize()` I get:

 `Uncaught ReferenceError: DEBUG is not defined`

I see `DEBUG` defined [here](https://github.com/timruffles/ios-html5-drag-drop-shim/blob/v2.0.0-beta.0/release/drag-drop-polyfill.d.ts#L1) but afaik I can't import that source in my EmberJS app as it's TypeScript. 
Shouldn't `DEBUG` be defined in `drag-drop-polyfill.js` for better compatibility?

**Comment by reppners** [comment]
Yes, you're right. Will fix in next beta release. Until then you should be able to fix this by doing `var DEBUG; DragDropPolyfill.Initialize();`

The typescript declare statement is not really defining `DEBUG`, it is just declaring that someone else is defining it.

**Comment by algodave** [comment]
Thanks @reppners !
