### ISSUE TITLE
ClientX and ClientY for Drop

### ISSUE THREAD

**Issue by lignumaqua** [timruffles/ios-html5-drag-drop-shim#72]
Many thanks for the code, saved me a lot of pain! ClientX and ClientY are not currently included for Drop. I added them into dispatchDrop and they worked as expected.

```
  dropEvt.clientX = touch.clientX;
  dropEvt.clientY = touch.clientY;
```

**Comment by timruffles** [comment]
Thanks for using the library, and your issue report! I believe this is fixed in our rewrite, so we'll wait till that's merged.
