### ISSUE TITLE
iOS10/Safari10: touchmove.preventDefault() not preventing browser scroll

### ISSUE THREAD

**Issue by reppners** [timruffles/ios-html5-drag-drop-shim#77]
http://www.openradar.me/28479522

http://stackoverflow.com/questions/40027513/scroll-cant-be-default-prevented-on-touchmove-event-on-ios10

https://bugs.webkit.org/show_bug.cgi?id=163207

Tripped over this regression while working on new demo pages for the rewrite.

**Comment by reppners** [comment]
Seems like somebody found a workaround!

```js
window.addEventListener( 'touchmove', function() {})
```

Credits go to https://github.com/metafizzy/flickity/issues/457#issuecomment-254501356

**Comment by dpogue** [comment]
In the webkit bug, it sounds like a better fix is to call `preventDefault()` in a `touchforcechange` event listener on the element, rather than adding extraneous listeners on the window.

**Comment by reppners** [comment]
The reason I did not implement the `touchforcechange`-fix was because the event never fired on my iPhone 6 which does not have 3D Touch support. The fix simply did not work.

**Comment by reppners** [comment]
closing as a workaround is available and there is nothing else the library can do to help the issue.
