### ISSUE TITLE
npm publish v1.2.0

### ISSUE THREAD

**Issue by reppners** [timruffles/ios-html5-drag-drop-shim#78]
@timruffles I am not able to publish v1.2.0 to npm. Can you take care of this step?

**Comment by timruffles** [comment]
@reppners let me know your npm details, and I'll add you! :)

**Comment by reppners** [comment]
@timruffles sure, username is `reppners`. Thx :)

**Comment by timruffles** [comment]
done, publish away! thanks again for the fantastic work :)

On Mon, Nov 21, 2016 at 11:35 AM, Stefan Steinhart <notifications@github.com

**Comment by reppners** [comment]
Thx! Published on bower and npm as v1.2.0 👍
