### ISSUE TITLE
Investigate passive document level event listeners

### ISSUE THREAD

**Issue by reppners** [timruffles/ios-html5-drag-drop-shim#79]
https://www.chromestatus.com/feature/5093566007214080

https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md

The new  `passive`-option for on `addEventListener` is there to let the browser know in advance if your event listener will call `preventDefault()`. The reason is scrolling performance.

This polyfill is a primary user of document level event listeners and I experienced issues on latest stable chromium `54.0.2840.99` where the new behaviour is already activated.

**Comment by reppners** [comment]
logs from using drag-drop-polyfill@2.0.0-beta.2 in Chromium `54.0.2840.99`

```
drag-drop-polyfill.ts:552 dnd-poly: moving draggable..
drag-drop-polyfill.ts:555 Unable to preventDefault inside passive event listener due to target being treated as passive. 
See https://www.chromestatus.com/features/5093566007214080DragOperationController._onTouchMove @ drag-drop-polyfill.ts:555
```

**Comment by reppners** [comment]
implemented and released in https://github.com/timruffles/ios-html5-drag-drop-shim/releases/tag/v2.0.0-beta.3

**Comment by timruffles** [comment]
LGTM! niceone

**Comment by reppners** [comment]
Thx! Just realized this issue might also affect v1.

Reopening until assured that v1 also works with future chrome browsers. PRs welcome! 👍

**Comment by RByers** [comment]
Sorry for the trouble, this is a breaking change in Chrome 56 to [improve scroll performance](https://developers.google.com/web/updates/2017/01/scrolling-intervention).  You can probably fix this by adding an appropriate `touch-action` [CSS rule](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action).

**Comment by nathanbedford** [comment]
@RByers thanks for the heads-up on the CSS rule.  That fixed it for me.  I'll work on a PR to put that note in the readme.
