### ISSUE TITLE
Suggestion - Dynamic element selection

### ISSUE THREAD

**Issue by RobbieLensen** [timruffles/ios-html5-drag-drop-shim#81]
Hi all,

First of all, my thanks to @timruffles for this nice script, it really takes the pain away from handling drag-n-drop on mobile devices.

In my implementation I noticed that on mobile safari (on iOS 10.2), after activating the script, suddenly all elements seemed to become draggable (= on drag, every element stuck to the cursor as a real draggable element).

I solved this issue by adding a custom attribute only to those elements that I really wanted to drag and change rule 323 in the script to

`if (el.draggable === true && el.getAttribute("<custom_attribute>") === "<specific_value>") {`
 
I thought I'd share this solution and maybe make a suggestion to integrate this into the master version (or maybe with the possibility to give a querySelector upon construction of the main object).

Regards,

Robbie

**Comment by timruffles** [comment]
Thanks for the report! On that browser, are you seeing .draggable becoming
true? It'd be an interesting browser bug if so!

**Comment by RobbieLensen** [comment]
Hi Tim,
I have tested some more and it seems to affect the <a> elements only. 
As far as I can see,  .draggable is not becoming true.
I'll dig some more and keep you posted.

**Comment by timruffles** [comment]
Closing for now, happy to hear more!
