### ISSUE TITLE
Ready for a release?

### ISSUE THREAD

**Issue by nathanbedford** [timruffles/ios-html5-drag-drop-shim#89]
@timruffles, @xStrom, I'd like to create release v1.3.0 so we can publish the fixes / features. Thoughts?

Diff between last release (1.2.0) and master:
https://github.com/timruffles/ios-html5-drag-drop-shim/compare/v1.2.0...master

**Features**
* Added commonjs support

**Bugfixes**
* fixed issue with Chrome and addEventListener defaulting to {passive:true} in v56
* when dragstart occurs on anchor element, defaulting to not send mouse events
* will search upwards for a draggable element in touchstartDelay now

**Comment by xStrom** [comment]
Yes, this should be done. Unfortunately I haven't ever managed the releasing procedure here.

It seems that we're listed on NPM & Bower. On NPM only @timruffles & @reppners have access. I've never used Bower, but it seems to use only git and has no version update procedure of its own?

**Comment by nathanbedford** [comment]
Yes, you are right about Bower, it just reads the releases from the GitHub repo. 

I can go head and create the release so Bower is good to go.

**Comment by nathanbedford** [comment]
@timruffles or @reppners would you be able to create the releases for npm? I've created the release in this repo so Bower users should be able to get v1.3.0 now.

https://github.com/timruffles/ios-html5-drag-drop-shim/releases/tag/v1.3.0

**Comment by nathanbedford** [comment]
@reppners, @bhollis and Anton Kozlov, thanks for contributing to this release!

**Comment by xStrom** [comment]
Doesn't [bower.json](https://github.com/timruffles/ios-html5-drag-drop-shim/blob/master/bower.json#L4) need to be updated too?

**Comment by bhollis** [comment]
Sorry to comment on a closed issue, but will there be a new npm release?

**Comment by xStrom** [comment]
I certainly think there should be. We need either @timruffles or @reppners to generate those.

Alternatively, I could do it but I need to be added to the access list on NPM. My username there is [strom](https://www.npmjs.com/~strom).

**Comment by nathanbedford** [comment]
Agreed

**Comment by timruffles** [comment]
Okay - pushed 1.4.1 (existing tag in git). Sorry for slow reply - got back from 3 weeks off on Sat.

Have added @xStrom to npm as an owner - @nathanbedford if you let me know your username I'll do the same.

**Comment by bhollis** [comment]
Thank you!

-Ben

**Comment by nathanbedford** [comment]
@timruffles my npm username is [nathanbedford](https://www.npmjs.com/~nathanbedford).

Thanks!

**Comment by timruffles** [comment]
I think we've had released and everyone's a npm owner now, so I'm closing this.
