### ISSUE TITLE
How to import to typescript

### ISSUE THREAD

**Issue by 00MIN00** [timruffles/ios-html5-drag-drop-shim#94]
I use import { DragDropPolyfill } from "drag-drop-polyfill";
and error is "Cannot find module 'drag-drop-polyfill'."
help me please.

**Comment by reppners** [comment]
Thats a known issue, please refer to #83. We will make sure it works properly on final release, you can track the progress here #87.

Are you using any module loader? SystemJS, WebPack (v1/v2)?

**Comment by 00MIN00** [comment]
I not sure for my answer is correct. (I am newer for typescript) I using angular-cli and WebPack 4.4.1

**Comment by reppners** [comment]
fixed by #100
