### ISSUE TITLE
Script error in handleTouchStartOnAnchor

### ISSUE THREAD

**Issue by laurentvd** [timruffles/ios-html5-drag-drop-shim#95]
There is a bug in the `handleTouchStartOnAnchor` function. It references `evt` while this isn't passed to the function. I'll create a PR to fix this.

**Comment by nathanbedford** [comment]
@laurentvd good catch, I can review this later today.

**Comment by xStrom** [comment]
I reviewed it. I somehow managed to miss this during my previous review. A good reminder that I need to be more careful. 

Thanks a lot @laurentvd.

**Comment by laurentvd** [comment]
No problem
