### ISSUE TITLE
dndPlaceholder is not generated on the 0 index in the md-list

### ISSUE THREAD

**Issue by HightowerCZ** [timruffles/ios-html5-drag-drop-shim#97]
Hi,

I have trouble  with drag and drop on iPad. 
Webpage structure:

```
<md-content style="background-color: #ffffff;">
               <md-list style="padding: 0; min-height: 57px;"
                        dnd-list="pkgEd.panels[pkgEd.activePanelIndex].media"
                        dnd-external-sources="false"
                        dnd-drop="pkgEd.dropCallback(event, index, item, external, type, 'panelList')">
                  <div ng-repeat="m in pkgEd.panels[pkgEd.activePanelIndex].media"
                       dnd-draggable="m"
                       dnd-moved="pkgEd.mediaMoved($index)"
                       dnd-effect-allowed="move"
                       dnd-disable-if="pkgEd.editor.isReadonly()">
                     <md-list-item style="border-top: 1px solid gainsboro; overflow: hidden;" dnd-nodrag class="editorTable editorTalbeItem">
                        <div dnd-nodrag layout="row" layout-align="start center" style="min-height:60px;vertical-align:middle;width:100%">
```

It works almost fine. When the user try drop list item to the top of the list (index 0), dndPlaceholder is not generated and when he drops, item is inserted as the second item (to the index 1).

Do you have any idea what should I do?

Thank you,
Jakub

**Comment by reppners** [comment]
Can you provide a plunkr oder jsfiddle to demonstrate the issue?

**Comment by HightowerCZ** [comment]
you can open it here:
https://plnkr.co/edit/rPkFW5fJLpVivgBow2Av?p=preview

Thank you

**Comment by HightowerCZ** [comment]
it looks like dragover event don't fill event.offsetX, event.offsetY, event.layerX, event.layerY

**Comment by reppners** [comment]
This is very likely fixed in the rewrite:
https://github.com/timruffles/ios-html5-drag-drop-shim/tree/rewrite

I'm using the rewrite, angular-material and angular-drag-drop-lists in a project and don't have the issue you are describing here.

Can you test with this plunkr to see if it fixes your problem?

https://plnkr.co/edit/GMQYJa

**Comment by HightowerCZ** [comment]
Hi, I tested it successfully and move it to my application. Thank you.
